kasirResto_MVC/Models/Menu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace kasirResto.Models
{
    [Table("Menu")]
    public partial class Menu
    {
        [Key]
        public int MenuId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string? MenuNama { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string? MenuImage { get; set; }
        public int? MenuKategoriId { get; set; }
        public int? MenuPrice { get; set; }
        public byte? MenuStatus { get; set; }
    }
}

kasirResto_MVC/Controllers/KategoriMenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using kasirResto.Data;
using kasirResto.Models;
using NETCore.Encrypt;
namespace kasirResto.Controllers
{
    public class KategoriMenusController : Controller
    {
        private readonly kasirRestoContext _context;

        public KategoriMenusController(kasirRestoContext context)
        {
            _context = context;
        }

        // GET: KategoriMenus
        public async Task<IActionResult> Index()
        {
              return View(await _context.KategoriMenus.ToListAsync());
        }

        // GET: KategoriMenus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.KategoriMenus == null)
            {
                return NotFound();
            }

            var kategoriMenu = await _context.KategoriMenus
                .FirstOrDefaultAsync(m => m.KategoriId == id);
            if (kategoriMenu == null)
            {
                return NotFound();
            }

            return View(kategoriMenu);
        }

        // GET: KategoriMenus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: KategoriMenus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("KategoriId,KategoriNama,KategoriImage,KategoriStatus")] KategoriMenu kategoriMenu, IFormFile KategoriImage)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (KategoriImage != null)
                    {
                        var srcString = $"{DateTime.Now}";
                        var hashed = EncryptProvider.Md5(srcString);
                        var x = KategoriImage.FileName;
                        var newname = $"p{hashed}.jpg";
                        string uploadpath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img\\kategori", newname);
                        var stream = new FileStream(uploadpath, FileMode.Create);
                        KategoriImage.CopyToAsync(stream);
                        ViewBag.Message = KategoriImage;
                        kategoriMenu.KategoriImage = $"img/kategori/{newname}";
                    }
                    else
                    {
                        ViewBag.Message = "Gambar belum di isi.";
                        return View("~/Views/Shared/Error_Message.cshtml");
                    }

                }
                catch
                {
                    ViewBag.Message = "Error while uploading the files.";
                    return View("~/Views/Shared/Error_Message.cshtml");
                }
                _context.Add(kategoriMenu);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Menu", new { area = "" });
            }
            return View(kategoriMenu);
        }

        // GET: KategoriMenus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.KategoriMenus == null)
            {
                return NotFound();
            }

            var kategoriMenu = await _context.KategoriMenus.FindAsync(id);
            if (kategoriMenu == null)
            {
                return NotFound();
            }
            KategoriMenu m = _context.KategoriMenus.AsNoTracking().Where(x => x.KategoriId == id).FirstOrDefault();
            ViewBag.datasaatini = m;
            return View(kategoriMenu);
        }

        // POST: KategoriMenus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("KategoriId,KategoriNama,KategoriImage,KategoriStatus")] KategoriMenu kategoriMenu, IFormFile? KategoriImage)
        {
            if (id != kategoriMenu.KategoriId)
            {
                return NotFound();
            }

            KategoriMenu m = _context.KategoriMenus.AsNoTracking().Where(x => x.KategoriId == id).FirstOrDefault();
            if (KategoriImage != null)
            {
                try
                {
                    var srcString = $"{DateTime.Now}";
                    var hashed = EncryptProvider.Md5(srcString);
                    var x = KategoriImage.FileName;
                    var newname = $"p{hashed}.jpg";
                    string uploadpath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img\\kategori", newname);
                    var stream = new FileStream(uploadpath, FileMode.Create);
                    KategoriImage?.CopyToAsync(stream);
                    kategoriMenu.KategoriImage = $"img/kategori/{newname}";
                }
                catch (Exception e)
                {
                    ViewBag.Message = "Error while uploading the files." + e;
                    return View("~/Views/Shared/Error_Message.cshtml");
                }
            }
            else
            {
                kategoriMenu.KategoriImage = m.KategoriImage;
            }
            _context.Update(kategoriMenu);
            await _context.SaveChangesAsync();
            return RedirectToAction("Edit", new { id = kategoriMenu.KategoriId });
        }

        // GET: KategoriMenus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.KategoriMenus == null)
            {
                return NotFound();
            }

            var kategoriMenu = await _context.KategoriMenus
                .FirstOrDefaultAsync(m => m.KategoriId == id);
            if (kategoriMenu == null)
            {
                return NotFound();
            }

            return View(kategoriMenu);
        }

        // POST: KategoriMenus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.KategoriMenus == null)
            {
                return Problem("Entity set 'kasirRestoContext.KategoriMenus'  is null.");
            }
            var kategoriMenu = await _context.KategoriMenus.FindAsync(id);
            if (kategoriMenu != null)
            {
                _context.KategoriMenus.Remove(kategoriMenu);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KategoriMenuExists(int id)
        {
          return _context.KategoriMenus.Any(e => e.KategoriId == id);
        }
    }
}

kasirResto_MVC/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using kasirResto.Data;
using kasirResto.Models;
using NETCore.Encrypt;
using Microsoft.AspNetCore.Authorization;

namespace kasirResto.Controllers
{
    [AllowAnonymous]
    public class MenuController : Controller
    {
        private readonly kasirRestoContext _context;

        public MenuController(kasirRestoContext context)
        {
            _context = context;
        }

        // GET: Menu
        public async Task<IActionResult> Index()
        {

            //ViewBag.sessi = HttpContext.Session.GetString("AnyKey");
            List<Menu> m = await _context.Menus.ToListAsync();
            List<KategoriMenu> km = await _context.KategoriMenus.ToListAsync();
            ViewData["Menu"] = m;
            ViewData["KategoriMenu"] = km;
            //var tupleModel = new Tuple<List<Menu>, List<KategoriMenu>>(m, km);
            return View();
        }

        // GET: Menu/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Menus == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus
                .FirstOrDefaultAsync(m => m.MenuId == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // GET: Menu/Create
        public IActionResult Create()
        {
            List<KategoriMenu> kategori = _context.KategoriMenus.ToList();
            ViewBag.kategori = kategori;
            return View();
        }

        // POST: Menu/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MenuId,MenuNama,MenuImage,MenuKategoriId,MenuPrice,MenuStatus")] Menu menu, IFormFile MenuImage)
        {
            if (MenuImage != null)
            {
                try
                {

                    var srcString = $"{DateTime.Now}";
                    var hashed = EncryptProvider.Md5(srcString);
                    var x = MenuImage.FileName;
                    var newname = $"p{hashed}.jpg";
                    string uploadpath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img\\produk", newname);
                    var stream = new FileStream(uploadpath, FileMode.Create);
                    MenuImage.CopyToAsync(stream);
                    ViewBag.Message = MenuImage;
                    menu.MenuImage = $"img/produk/{newname}";
                }
                catch
                {
                    ViewBag.Message = "Error while uploading the files.";
                    return View("~/Views/Shared/Error_Message.cshtml");
                }
            }
            else
            {
                ViewBag.Message = "Gambar belum di isi.";
                return View("~/Views/Shared/Error_Message.cshtml");
            }
            _context.Add(menu);
            await _context.SaveChangesAsync();
            return RedirectToAction("index");
        }

        // GET: Menu/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Menus == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus.FindAsync(id);
            if (menu == null)
            {
                return NotFound();
            }
            List<KategoriMenu> kategori = _context.KategoriMenus.ToList();
            ViewBag.kategori = kategori;
            Menu m = _context.Menus.AsNoTracking().Where(x => x.MenuId == id).FirstOrDefault();
            ViewBag.datasaatini = m;
            return View(menu);
        }

        // POST: Menu/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MenuId,MenuNama,MenuImage,MenuKategoriId,MenuPrice,MenuStatus")] Menu menu, IFormFile? MenuImage)
        {
            if (id != menu.MenuId)
            {
                return NotFound();
            }

            Menu m = _context.Menus.AsNoTracking().Where(x => x.MenuId == menu.MenuId).FirstOrDefault();
            try
            {
                if (MenuImage != null)
                {
                    if (MenuImage.FileName != null)
                    {
                        var srcString = $"{DateTime.Now}";
                        var hashed = EncryptProvider.Md5(srcString);
                        var newname = $"p{hashed}.jpg";
                        string uploadpath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img\\produk", newname);
                        var stream = new FileStream(uploadpath, FileMode.Create);
                        MenuImage.CopyToAsync(stream);
                        menu.MenuImage = $"img/produk/{newname}";
                    }
                    else
                    {
                        menu.MenuImage = $"{m.MenuImage}";
                    }
                }
                else
                {
                    menu.MenuImage = $"{m.MenuImage}";
                }
            }
            catch (InvalidCastException e)
            {
                ViewBag.Message = "Error while uploading the files. @(e)";
                return View("~/Views/Shared/Error_Message.cshtml");
            }
            _context.Update(menu);
            await _context.SaveChangesAsync();
            return RedirectToAction("Edit", new { id = menu.MenuId });
        }

        // GET: Menu/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Menus == null)
            {
                return NotFound();
            }

            var menu = await _context.Menus
                .FirstOrDefaultAsync(m => m.MenuId == id);
            if (menu == null)
            {
                return NotFound();
            }

            return View(menu);
        }

        // POST: Menu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Menus == null)
            {
                return Problem("Entity set 'kasirRestoContext.Menus'  is null.");
            }
            var menu = await _context.Menus.FindAsync(id);
            if (menu != null)
            {
                _context.Menus.Remove(menu);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MenuExists(int id)
        {
          return _context.Menus.Any(e => e.MenuId == id);
        }
    }
}

kasirResto_MVC/Views/Menu/Create.cshtml
@model kasirResto.Models.Menu
@{
    ViewData["Title"] = "Create";
    var k = ViewBag.kategori;
}

<h1 class="text-white h1">Tambah Menu</h1>

<div class="row text-white">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Menu" method="post" enctype="multipart/form-data" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MenuNama" class="control-label">Nama Menu</label>
                <input asp-for="MenuNama" class="form-control" />
                <span asp-validation-for="MenuNama" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MenuImage" class="control-label">Gambar</label>
                <input asp-for="MenuImage" class="form-control" type="file"/>
                <span asp-validation-for="MenuImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MenuKategoriId" class="control-label">Kategori</label>
                <select asp-for="MenuKategoriId" class="form-control">
                    @foreach (var i in k) { 
                        <option value="@i.KategoriId">@i.KategoriNama</option>
                    }
                </select>
                <span asp-validation-for="MenuKategoriId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MenuPrice" class="control-label">Harga</label>
                <input asp-for="MenuPrice" class="form-control" />
                <span asp-validation-for="MenuPrice" class="text-danger"></span>
            </div>
            <div class="form-group d-none">
                <label asp-for="MenuStatus" class="control-label"></label>
                <input asp-for="MenuStatus" class="form-control" value="1" />
                <span asp-validation-for="MenuStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-danger btn-block" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

kasirResto_MVC/Views/Menu/Delete.cshtml
@model kasirResto.Models.Menu

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Menu</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuNama)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuNama)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuImage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuKategoriId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuKategoriId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuStatus)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MenuId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

kasirResto_MVC/Views/Menu/Details.cshtml
@model kasirResto.Models.Menu

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Menu</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuNama)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuNama)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuImage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuKategoriId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuKategoriId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MenuStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MenuStatus)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MenuId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

kasirResto_MVC/Views/Menu/Edit.cshtml
@model kasirResto.Models.Menu

@{
    ViewData["Title"] = "Edit";
    var k = ViewBag.kategori;
    var datasaatini = ViewBag.datasaatini;
}
<div class="row text-white mt-3">
    <div class="col-md-3">
        <h1 class="text-white h1">Edit Menu</h1>
    </div>
    <div class="col-md-1 text-end">
        <a asp-action="Delete" asp-route-id="@datasaatini.MenuId" class="btn btn-danger rounded"><i class="fa fa-trash"></i></a>
    </div>
</div>
<hr />

<div class="row text-white">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Menu" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MenuId" />
            <div class="form-group">
                <label asp-for="MenuNama" class="control-label">Nama Menu</label>
                <input asp-for="MenuNama" class="form-control" />
                <span asp-validation-for="MenuNama" class="text-danger"></span>
            </div>
            <img src="/@datasaatini.MenuImage" alt="Alternate Text" class="w-100 rounded" />
            <div class="form-group">
                <label asp-for="MenuImage" class="control-label">Gambar</label>
                <input asp-for="MenuImage" class="form-control" type="file" />
                <span asp-validation-for="MenuImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MenuKategoriId" class="control-label">Kategori</label>
                <select asp-for="MenuKategoriId" class="form-control">
                    @foreach (var i in k)
                    {
                        <option value="@i.KategoriId">@i.KategoriNama</option>
                    }
                </select>
                <span asp-validation-for="MenuKategoriId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MenuPrice" class="control-label">Harga</label>
                <input asp-for="MenuPrice" class="form-control" />
                <span asp-validation-for="MenuPrice" class="text-danger"></span>
            </div>
            <div class="form-group d-none">
                <label asp-for="MenuStatus" class="control-label"></label>
                <input asp-for="MenuStatus" class="form-control" value="1" />
                <span asp-validation-for="MenuStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-danger btn-block" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

kasirResto_MVC/Views/Menu/Index.cshtml
@{
    ViewData["Title"] = "Index";
    IEnumerable<Menu> menu = ViewData["Menu"] as IEnumerable<Menu>;
    IEnumerable<KategoriMenu> kategori = ViewData["KategoriMenu"] as IEnumerable<KategoriMenu>;
}

<h1 class="h1 text-white">Menu</h1>
<div class="">
    <div class="row  g-3 mb-3  align-items-center flex-row flex-nowrap" style="overflow-x: auto;">
        <div class="col-2">
            <a class="card card-body bg-grey shadow text-white text-decoration-none rounded-pill" asp-controller="KategoriMenus" asp-action="Create">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <img src="/img/produk/produk-none.jpg" alt="Tambah" class="w-100 rounded-circle" />
                    </div>
                    <div class="col-md-9 text-start">
                        <span class="h4">Tambah</span>
                    </div>
                </div>
            </a>
        </div>
        @foreach (var item in kategori)
        {
            <div class="col-3">
                <a class="card card-body bg-grey shadow text-white text-decoration-none rounded-pill" asp-controller="KategoriMenus" asp-action="Edit" asp-route-id="@item.KategoriId">
                    <div class="row  align-items-center">
                        <div class="col-md-2">
                            <img src="/@item.KategoriImage" alt="Edit" class="w-100 rounded-circle" />
                        </div>
                        <div class="col-md-10 text-start">
                            <span class="h4">
                                @item.KategoriNama
                            </span>
                        </div>
                    </div>
                </a>
            </div>
        }
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="row g-3">
            <div class="col-md-3">
                <a class="card card-body bg-grey shadow text-white text-decoration-none" asp-action="Create">
                    <img src="/img/produk/produk-none.jpg" alt="Tambah" class="w-100 rounded" />
                    <div class="text-truncate">
                        <span class="">Tambah Menu Baru</span>
                    </div>
                    <div class=" text-end">
                        <span class="btn btn-danger rounded-circle"><i class="fa fa-plus fa-1x"></i></span>
                    </div>
                </a>
            </div>
            @foreach (var item in menu)
            {
                <div class="col-md-3">
                    <div class="card card-body shadow bg-grey text-white">
                        <img src="/@Html.DisplayFor(modelItem => item.MenuImage)" alt="@Html.DisplayFor(modelItem => item.MenuNama)" class="w-100 rounded" />
                        <div class="text-truncate">
                            <span class="">@Html.DisplayFor(modelItem => item.MenuNama)</span>
                        </div>
                        <div>
                            <span class="h5 font-weight-bold text-danger">Rp @string.Format("{0:#,0}", item.MenuPrice)</span>
                            <a asp-action="Edit" asp-route-id="@item.MenuId" class="btn btn-danger rounded-pill float-end"><i class="fa fa-edit fa-1x"></i>Edit</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="col-md-4">

    </div>
</div>